apiVersion: v1
kind: Service
metadata:
  name: fleet-api
spec:
  type: {{ .Values.fleetApi.service.type }}

  selector:
    app: fleet-api

  ports:
    - name: http
      port: {{ .Values.fleetApi.service.port }}
      targetPort: http
{{- if eq .Values.fleetApi.service.type "NodePort" }}
      nodePort: {{ .Values.fleetApi.service.nodePort }}
{{- end }}
