apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
  namespace: machina-sandbox
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true

    listener 9001
    protocol websockets
    allow_anonymous true

    persistence true
    persistence_location /mosquitto/data/
    log_type error
    log_type warning
    log_type notice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: machina-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: eclipse-mosquitto:2
          ports:
            - containerPort: 1883
            - containerPort: 9001
          volumeMounts:
            - name: broker-config-volume
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: broker-config-volume
          configMap:
            name: broker-config

---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: machina-sandbox
spec:
  selector:
    app: broker
  type: NodePort
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31883
    - name: ws
      port: 9001
      targetPort: 9001
      nodePort: 30901