apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: machina-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Valheriane/machina-sandbox-full.git
    targetRevision: dev
    path: machina-sandbox
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: machina-helm-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true